spring:
  application:
    name: product_crud
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


cloudinary:
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}
  cloud_name: ${CLOUDINARY_NAME}

springdoc:
  swagger-ui:
    path: /docs.html