spring:
  application:
    name: product_crud
  datasource:
    url: jdbc:h2:mem:prod-crud
    driver-class-name: org.h2.Driver
    username: devkiki
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


cloudinary:
  api_key: 573745139163865
  api_secret: URe4eOJe7pclLJLOXNG3HWwtUJc
  cloud_name: dpwnpq3oz